# Generated by Django 4.2.16 on 2025-05-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('dcls_month', models.CharField(max_length=6)),
                ('prdt_type', models.IntegerField()),
                ('fin_co_no', models.TextField()),
                ('fin_prdt_cd', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.IntegerField()),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('dcls_start_day', models.TextField(blank=True, null=True)),
                ('dcls_end_day', models.TextField(blank=True, null=True)),
                ('fin_co_subm_day', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.CharField(max_length=6)),
                ('fin_co_no', models.TextField()),
                ('intr_rate_type', models.CharField(max_length=1)),
                ('intr_rate_type_nm', models.CharField(max_length=10)),
                ('rsrv_type', models.CharField(blank=True, max_length=1, null=True)),
                ('rsrv_type_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('save_trm', models.TextField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('fin_prdt_cd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interest_rates.product')),
            ],
        ),
    ]
