# Generated by Django 4.2.16 on 2025-05-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_age_customuser_current_assets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_products',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
