# Generated by Django 4.2.16 on 2025-05-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_subscribed_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscribed_products',
            field=models.TextField(),
        ),
    ]
